# In-Class Programming Activity, Day 5

Your work goes here ...

## Madeline Olson

## Task 1

```{r}
library(mosaicData)
nbins=10
```

## Task 2

```{r}
evenly_spaced = seq(56, 79, length = nbins+1)
```

## Task 3

```{r}
bin_counts=table(cut(Galton$height, evenly_spaced))
```

## Task 4

```{r}
xL=evenly_spaced[1:10]
xR=evenly_spaced[2:11]
count=as.numeric(bin_counts)
hist_basics=data.frame(xL,xR,count)
```

## Task 5

```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}

My_bars=data.frame(make_one_bar(one_to_five(hist_basics)))
```

#
My_bars seems wrong, can't get task 6 to run because of it

## Task 6

#```{r}

plot(My_bars, type="n")
lines(My_bars)
polygon(My_bars)
```

## Test statements

```{r}
scoreActivity::score253(5)
```